spring.application.name=app_security

# security
#spring.security.user.name=admin
#spring.security.user.password=admin
#spring.security.user.roles={ROLE_VIEWER}

#datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/security_bank
spring.datasource.username=renzoqamao
spring.datasource.password=custom
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
